### ISSUE TITLE
Wondering how to use this

### ISSUE THREAD

**Issue by esteinborn** [heshanlk/webform_migrate#2]
Couldn't find any instructions in the module on how to use it. 

Do you have documentation anywhere that I could use?

Thanks!

**Comment by heshanlk** [comment]
Hy @esteinborn there is no any documentation at the moment but feel free to add anything that you think might helpful. I'm not sure what your background is, if you are a developer then it just use the templates in **_migration_templates_** folder those are there for your reference. If you are a site builder do nothing on coding this module might not be straightforward to you. This module needs couple of config files added based on your system (exception if you know how to write configs using yml and know how to use config management you'r good).

**Comment by heshanlk** [comment]
I updated the readme.md with steps to install the module. Hope that helps.
