### ISSUE TITLE
Compatibility with CSV Plugin

### ISSUE THREAD

**Issue by kclarkson** [heshanlk/webform_migrate#9]
@heshanlk really love this module. I have been working with Jacob and is working on a simple Drush command but I would really like to use migrate. 

Is there a way to make this module work with the CSV Migrate plugin module? 

Thanks again for the help!

**Comment by heshanlk** [comment]
Hi @kclarkson I don't think you need this module if you are using CSV Migrate, what it does it will give you options to use a CSV feed (Source plugin) to be mapped into a Webform or Webform Submission (Destination plugins). Hope this helps, thanks.
